name: Pre-commit Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install pre-commit if not already available in your dependencies
          pip install pre-commit
          # Optionally install your API package dependencies if needed
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pre-commit checks
        run: pre-commit run
